### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by FOS-Intern**
This is an idk branch!!

### CODE REVIEW

**Comment by cjsonnnnn** [comment]
hi... what is this?! !

**Comment by FOS-Intern** [comment]
> hi... what is this?! !

idk for sure!

**Review by cjsonnnnn — CHANGES_REQUESTED** [review]
please delete the `too`. i don't like that!!

**Review by cjsonnnnn — CHANGES_REQUESTED** [review]
you need to remove the `too`

**Review by cjsonnnnn — CHANGES_REQUESTED** [review]
stop giving me the re-request review! I know what I am doing! just remove `too`!!

**Pull request closed without merging**
